apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*

build:
  local:
    push: false

  artifacts:
    - image: gamhhnile/client
      context: client
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .

    - image: gamhhnile/comments
      context: comments
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .

    - image: gamhhnile/event-bus
      context: event-bus
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .

    - image: gamhhnile/moderation
      context: moderation
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .

    - image: gamhhnile/posts
      context: posts
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .

    - image: gamhhnile/query
      context: query
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .